apiVersion: v2
name: node-exporter-app
description: A Helm chart for prometheus node-exporter
keywords:
  - node-exporter
  - prometheus
  - exporter
type: application
version: 1.20.11-dev
appVersion: 1.8.2
home: https://github.com/giantswarm/node-exporter-app
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
sources:
  - https://github.com/prometheus/node_exporter/
maintainers:
  - email: gianrubio@gmail.com
    name: gianrubio
  - email: zanhsieh@gmail.com
    name: zanhsieh
  - email: rootsandtrees@posteo.de
    name: zeritti
annotations:
  application.giantswarm.io/team: tenet
  io.giantswarm.application.team: tenet
  config.giantswarm.io/version: 1.x.x
  "artifacthub.io/license": Apache-2.0
  "artifacthub.io/links": |
    - name: Chart Source
      url: https://github.com/prometheus-community/helm-charts
